### ISSUE TITLE
scss学习笔记

### ISSUE THREAD

**Issue by Cainankun** [Cainankun/cainankun.github.io#3]
# 父选择器 `&`
```css
a {
  &:hover { text-decoration: underline; }
  body.firefox & { font-weight: normal; }
}
//编译为
a { }
  a:hover {
    text-decoration: underline; }
  body.firefox a {
    font-weight: normal; }
```

# 属性嵌套

遵循相同命名空间的css属性(例如：font-family, font-size, font-weight)，可以简写成：
```css
.funky {
  font: {
    family: fantasy;
    size: 30em;
    weight: bold;
  }
}
编译为

.funky {
  font-family: fantasy;
  font-size: 30em;
  font-weight: bold; }
```

# 占位符选择器 `%foo`
?????

# 变量 `$`
```scss
$width: 100px;
div {
  width: $width;
}
```

## 作用域

变量支持块级作用域，嵌套规则内定义的变量只能在嵌套规则中使用（局部变量），不在嵌套规则内定义的变量则可在任何地方使用（全局变量）。将局部变量转换为全局变量可以添加 !global 声明：
```scss
#main {
  $width: 5em !global;
  width: $width;
}

#sidebar {
  width: $width;
}
```
# 数据类型
* 数字
* 字符串（分有引号和没引号字符串）
* 颜色
* 布尔值
* 空值（null）
* 数组，用空格或者逗号作为分隔符
* maps，相当于js中的Object
